### ISSUE TITLE
Release this version to supermarket?

### ISSUE THREAD

**Issue by bignastybryce** [failshell/chef-keytool#10]
Hi,

The version 0.7.0 of this cookbook on the supermarket has a broken :createstore action in the provider (it looks for new_resource.password instead of storepass).  I was going to submit a patch, but I see that it's already fixed here.  Are you planning to release to the supermarket any time?

**Comment by bignastybryce** [comment]
Also, +1 for making this.  Very useful.  I'll back that up with a beer if you want.  ;)

**Comment by failshell** [comment]
I will push it to supermarket over the weekend.

**Comment by failshell** [comment]
Supermarket has been updated.
