### ISSUE TITLE
keytool version 0.4.5 chef supermarket

### ISSUE THREAD

**Issue by thielena** [failshell/chef-keytool#4]
Hi,

there is just an old version `0.4.5` available at the [chef supermarket](https://supermarket.chef.io/cookbooks/keytool). Could you please release the current version `0.7.0`?

Thanks,
Andy

**Comment by computerlyrik** [comment]
please test/add https://github.com/failshell/chef-keytool/pull/7 before

**Comment by failshell** [comment]
@thielena I'll be back home soon. Where I'm setup to upload the cookbook to the supermarket. Will do it then. Thanks for pointing this out.

**Comment by failshell** [comment]
uploaded
